apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-beeulgch
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-beeulgch 
  name: go-beeulgch
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-beeulgch 
